wiki/rest-doc/Suppliers.endpoint.md

Add api prefix to endpoints

---

src/server/db/data/supplier2user.json
src/server/db/migrations/20170828174500-supplier2user-migration.main.js
src/server/db/migrations/20170828174500-supplier2user-migration.test.js
src/server/db/models/Supplier2User.js

Add Supplier2User model

---

src/client/components/SupplierRegistrationEditor/SupplierRegistrationEditorForm.react.js

Add optional to countries component in supplier registration editor

---

src/client/components/SupplierEditor/SupplierEditorForm.react.js
src/client/components/SupplierEditor/i18n/de.js
src/client/components/SupplierEditor/i18n/en.js
src/client/components/SupplierRegistrationEditor/SupplierRegistrationEditorForm.react.js
src/client/components/SupplierRegistrationEditor/i18n/de.js
src/client/components/SupplierRegistrationEditor/i18n/en.js

Add checkbox for no vat number available

---

src/server/routes/supplier_access.js
src/server/routes/suppliers.js
src/server/services/user.js

Move api calls for user to user service file

---

src/client/UserAbilities.js
src/client/components/ActionButton.react.js
src/client/components/SupplierBankAccountEditor/i18n/de.js
src/client/components/SupplierBankAccountEditor/i18n/en.js
src/client/components/SupplierContactEditor/SupplierContactEditForm.react.js
src/client/components/SupplierContactEditor/SupplierContactEditor.react.js
src/client/components/SupplierContactEditor/SupplierContactView.react.js
src/client/components/SupplierContactEditor/i18n/de.js
src/client/components/SupplierContactEditor/i18n/en.js
src/client/data/userAbilities.json
src/server/db/migrations/20171027095000-supplierContact-migration.main.js
src/server/db/models/SupplierContact.js

Syncronize supplier contacts and users

---

src/client/utils/validatejs/supplierConstraints.js
src/server/db/migrations/20171106094600-supplier-migration.main.js
src/server/db/models/Supplier.js

Increase supplierName length

---

package.json
src/client/components/SupplierContactEditor/SupplierContactEditor.react.js
src/client/components/SupplierContactEditor/i18n/de.js
src/client/components/SupplierContactEditor/i18n/en.js
src/server/routes/supplier_contacts.js

Show error if user already exists

---

src/client/components/SupplierList/SupplierList.react.js
src/client/components/SupplierList/i18n/de.js
src/client/components/SupplierList/i18n/en.js
src/client/components/SupplierList/i18n/index.js
src/client/components/SupplierList/index.js
www/App.js

Add SupplierList component

---

src/client/components/SupplierBankAccountEditor/SupplierBankAccountEditForm.react.js
src/client/components/SupplierBankAccountEditor/SupplierBankAccountView.react.js
src/client/components/SupplierBankAccountEditor/supplierBankAccountConstraints.js
src/client/i18n/de.json
src/client/i18n/en.json
src/client/i18n/fi.json
src/client/i18n/sv.json
src/server/db/migrations/20181007102000-supplier-bank-account-migration.main.js
src/server/db/models/SupplierBankAccount.js

Add bankgiro and plusgiro fields to bank account

---

package.json
src/client/components/SupplierBankAccountEditor/SupplierBankAccountEditForm.react.js
src/client/components/SupplierBankAccountEditor/SupplierBankAccountView.react.js
src/client/components/SupplierBankAccountEditor/supplierBankAccountConstraints.js
src/client/components/SupplierBankAccountEditor/supplierBankAccountValidator.js
src/client/i18n/de.json
src/client/i18n/en.json
src/client/i18n/fi.json
src/client/i18n/sv.json
src/client/utils/validatejs/custom.js
src/client/utils/validatejs/i18n/de.json
src/client/utils/validatejs/i18n/en.json
src/client/utils/validatejs/i18n/fi.json
src/client/utils/validatejs/i18n/sv.json
src/server/db/migrations/20181107162200-supplier-bank-account-migration.main.js
src/server/db/models/SupplierBankAccount.js
src/server/queries/supplier_bank_accounts.js

Add isrNumber field to supplier bank account

---

src/client/UserAbilities.js
src/client/components/SupplierAddressEditor/SupplierAddressEditor.react.js
src/client/components/SupplierAddressEditor/SupplierAddressView.react.js
src/client/data/userAbilities.json

Non supplier-admin users should only be allowed to view addresses

---

src/server/queries/capabilities.js
src/server/queries/supplier2users.js
src/server/queries/supplier_addresses.js
src/server/queries/supplier_bank_accounts.js
src/server/queries/supplier_contacts.js
src/server/queries/supplier_visibility.js
src/server/routes/suppliers.js

Add supplier delete endpoint

---

package.json
src/client/i18n/de.json
src/client/utils/validatejs/i18n/de.json
src/client/utils/validatejs/i18n/en.json
src/client/utils/validatejs/i18n/fi.json
src/client/utils/validatejs/i18n/sv.json
src/server/db/migrations/20181130161000-supplier-bank-account-migration.main.js
src/server/db/models/SupplierBankAccount.js
src/server/queries/supplier_bank_accounts.js

Deployment of 1.3.0-rc-1622 was successfull. Please merge your changes.

Pull-Request from duriel-build-automation

---

src/server/db/data/supplierAddressDemoData.json
src/server/db/data/supplierDemoData.json
src/server/db/data/supplirBankAccountDemoData.json
src/server/db/migrations/20181131114900-supplier-migration.test.js

Partly implements https://github.com/OpusCapita/businessnetwork/issues/230

Add test migration to load demo data

---

Dockerfile
package.json
src/client/components/AttributeValueEditorRow.react.js
src/client/components/SupplierCreator/SupplierCreator.react.js
src/client/components/SupplierCreator/SupplierCreatorForm.react.js
src/client/components/SupplierEditor/SupplierEditor.react.js
src/client/components/SupplierEditor/SupplierEditorForm.react.js
src/client/components/SupplierEditor/SupplierView.react.js
src/client/components/SupplierRegistrationEditor/SupplierRegistrationEditor.css
src/client/components/SupplierRegistrationEditor/SupplierRegistrationEditorForm.react.js
src/client/i18n/de.json
src/client/i18n/en.json
src/client/utils/validatejs/custom.js
src/client/utils/validatejs/customAsync.js
src/client/utils/validatejs/i18n/de.json
src/client/utils/validatejs/i18n/en.json
src/client/utils/validatejs/i18n/fi.json
src/client/utils/validatejs/i18n/sv.json
src/client/utils/validatejs/supplierConstraints.js
src/client/utils/validatejs/supplierValidator.js
src/server/db/models/Supplier.js
webpack.development.config.js
webpack.production.config.js

Add validation for commercial registration number

---

package.json
src/server/db/models/Supplier.js
src/server/queries/suppliers.js

Allow underscore for supplierId

---

rest-doc/examples/Supplier.json
rest-doc/schemas/Supplier.raml
src/server/db/migrations/20181131244400-supplier-migration.main.js
src/server/db/models/Supplier.js

Add managed field to supplier

---

src/client/components/SupplierRegistrationEditor/SupplierRegistrationEditor.css
src/client/components/SupplierRegistrationEditor/SupplierRegistrationEditor.react.js
src/client/components/SupplierRegistrationEditor/SupplierRegistrationEditorForm.react.js

Modify supplier registration form

---

src/client/components/SupplierList/SupplierList.react.js
src/client/i18n/de.json
src/client/i18n/en.json

Add search to supplier-list component

---

src/client/components/SupplierAutocomplete/SupplierAutocomplete.react.js

Urgent: Added external filter callback property.

---

src/client/components/SupplierCreator/SupplierCreator.react.js
src/client/components/SupplierCreator/SupplierCreatorForm.react.js
src/client/components/SupplierEditor/SupplierEditorForm.react.js
src/client/i18n/de.json
src/client/i18n/en.json
src/client/utils/validatejs/supplierConstraints.js
src/server/db/models/Supplier.js

Virtual supplier handling

---

src/client/i18n/de.json
src/client/i18n/en.json
src/client/i18n/es.json
src/client/i18n/fi.json
src/client/i18n/fr.json
src/client/i18n/it.json
src/client/i18n/pt.json
src/client/utils/validatejs/i18n/de.json
src/client/utils/validatejs/i18n/en.json
src/client/utils/validatejs/i18n/es.json
src/client/utils/validatejs/i18n/fi.json
src/client/utils/validatejs/i18n/fr.json
src/client/utils/validatejs/i18n/it.json
src/client/utils/validatejs/i18n/pt.json

updated the support phone number
